version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:00"
  - package-ecosystem: 'npm'
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
