name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: ['16', '18', '19']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm test

      - name: Install docs dependencies
        run: npm install
        working-directory: docs

      - name: Test docs build
        if: always()
        run: NODE_OPTIONS=--openssl-legacy-provider npm run build
        working-directory: docs
